aliases:
  - &restore-cache
    keys:
      - dependencies-{{ checksum "package.json" }}
      # Fallback in case checksum fails
      - dependencies-

  - &restore-example-cache
    keys:
      - dependencies-example-{{ checksum "example/package.json" }}
      - dependencies-example-

  - &restore-website-cache
    keys:
      - dependencies-website-{{ checksum "website/package.json" }}
      - dependencies-website-

  - &save-cache
    paths:
      - node_modules
    key: dependencies-{{ checksum "package.json" }}

  - &save-example-cache
    paths:
      - example/node_modules
    key: dependencies-example-{{ checksum "example/package.json" }}

  - &save-website-cache
    paths:
      - website/node_modules
    key: dependencies-website-{{ checksum "website/package.json" }}

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - restore-cache: *restore-cache
      - restore-cache: *restore-example-cache
      - restore-cache: *restore-website-cache
      - run: |
          yarn install
          cd example && yarn install && yarn build && cd ..
          cd website && yarn install && yarn build && cd ..
      - save-cache: *save-cache
      - save-cache: *save-example-cache
      - save-cache: *save-website-cache
      - run: yarn run lint
      - run: yarn run flow
      - run: yarn test -- --coverage
      - store_artifacts:
          path: coverage

  # test-e2e:
